[wallets]
# Up to 5 wallet addresses
addresses = ["<WALLET_PUBKEY1>", "<WALLET_PUBKEY2>"]

[rpc]
# Solana mainnet RPC endpoint
url = "https://api.mainnet-beta.solana.com"

[output]
# Path to the JSON-lines log file
file = "balances.log"

[telegram]
bot_token = "<YOUR_TELEGRAM_BOT_TOKEN>"
chat_id   = "<YOUR_TELEGRAM_CHAT_ID>"

[alerts]
# Low-balance thresholds (in SOL), in same order as 'addresses'
thresholds  = [1.0, 0.5]
# Minimum interval between alerts for the same wallet (milliseconds)
cooldown_ms = 60000
